[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "httpx>=0.28.1",
    "openai>=1.57.2",
    "streamlit>=1.41.0",
    "uvicorn>=0.32.1",
]
